executable		= my_script.sh
RequestCpus		= 24
+WCKey		= CST
+JobFlavour		= "espresso"
environment		= CST_INSTALLPATH="/afs/cern.ch/project/parc/cst2018"; CST_WAIT_FOR_LICENSE=on; CST_LICENSE_SERVER="1705@lxlicen01","1705@lxlicen02","1705@lxlicen03"; HOME="/afs/cern.ch/user/e/esenes/"
transfer_output_files   = ""
output          = cst.$(ClusterId).$(ProcId).out
error           = cst.$(ClusterId).$(ProcId).err
log             = cst.$(ClusterId).$(ProcId).log
queue

